name: Security Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - '.github/workflows/security-scan.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - '.github/workflows/security-scan.yml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Scan dependencies with Safety
      run: |
        safety check -r requirements.txt || echo "⚠️ Vulnerabilities found"
    
    - name: Scan code with Bandit
      run: |
        bandit -r src/ -x tests/ -ll || echo "⚠️ Security issues found"
      
    - name: Generate security report
      run: |
        mkdir -p security-reports
        safety check -r requirements.txt --json > security-reports/dependencies.json || true
        bandit -r src/ -x tests/ -f json -o security-reports/code.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: security-reports/
